version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pwd
      - pip install -r get-res/requirements.txt -t .
      - cp get-res/lambda.py .
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'