version: 0.2
env:
  variables:
    FUNCTION_NAME: function_name
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pwd
      - pip install -r $FUNCTION_NAME/requirements.txt -t .
      - cp $FUNCTION_NAME/lambda.py .
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
  name: $FUNCTION_NAME-$CODEBUILD_BUILD_NUMBER